CREATE TABLE inventory_transactions (
    inventory_transaction_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    warehouse_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    transaction_type VARCHAR(20) NOT NULL,
    quantity DECIMAL(15,2) NOT NULL,
    transaction_date TIMESTAMP NOT NULL,
    CONSTRAINT fk_inventory_transactions_warehouses
    FOREIGN KEY(warehouse_id)
    REFERENCES warehouses(warehouse_id),
    CONSTRAINT fk_inventory_transactions_product
    FOREIGN KEY(product_id)
    REFERENCES products(product_id)
);