CREATE TABLE sales_return_details (
    sales_return_detail_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sales_return_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    quantity DECIMAL(15,2) NOT NULL,
    CONSTRAINT fk_sales_return_details_sales_return
    FOREIGN KEY(sales_return_id)
    REFERENCES sales_returns(sales_return_id),
    CONSTRAINT fk_sales_return_details_product
    FOREIGN KEY(product_id)
    REFERENCES products(product_id)
);