CREATE TABLE invoice_details (
    invoice_detail_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id BIGINT NOT NULL,
    shipment_detail_id BIGINT NOT NULL,
    amount DECIMAL(15,2) NOT NULL,
    CONSTRAINT fk_invoice_details_invoice
        FOREIGN KEY(invoice_id)
        REFERENCES invoices(invoice_id),
    CONSTRAINT fk_invoice_details_shipment_detail
        FOREIGN KEY(shipment_detail_id)
        REFERENCES shipment_details(shipment_detail_id)
);