CREATE TABLE invoices (
    invoice_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_no VARCHAR(30) NOT NULL UNIQUE,
    customer_id BIGINT NOT NULL,
    invoice_date DATE NOT NULL,
    total_amount DECIMAL(15,2) NOT NULL,
    CONSTRAINT fk_invoices_customer
        FOREIGN KEY(customer_id)
        REFERENCES customers(customer_id)
);