CREATE TABLE order_details (
    order_detail_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    line_no INTEGER NOT NULL,
    product_id BIGINT NOT NULL,
    quantity DECIMAL(15,2) NOT NULL,
    unit_price DECIMAL(15,2) NOT NULL,
    amount DECIMAL(15,2) NOT NULL,
    CONSTRAINT uk_order_details
        UNIQUE(order_id, line_no),
    CONSTRAINT fk_order_details_order
        FOREIGN KEY(order_id)
        REFERENCES orders(order_id),
    CONSTRAINT fk_order_details_product
        FOREIGN KEY(product_id)
        REFERENCES products(product_id)
);