CREATE TABLE sales_return_details (
    sales_return_detail_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    sales_return_id BIGINT NOT NULL,

    product_id BIGINT NOT NULL,

    quantity DECIMAL(15,2) NOT NULL
);