CREATE TABLE product_prices (
    product_price_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    product_id BIGINT NOT NULL,

    valid_from DATE NOT NULL,
    valid_to DATE,

    unit_price DECIMAL(15,2) NOT NULL,

    CONSTRAINT fk_product_prices_product
        FOREIGN KEY(product_id)
        REFERENCES products(product_id)
);