CREATE TABLE tax_rates (
    tax_rate_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tax_code VARCHAR(20) NOT NULL,
    rate DECIMAL(5,2) NOT NULL,
    valid_from DATE NOT NULL,
    valid_to DATE
);