CREATE TABLE receipt_allocations (
    receipt_allocation_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receipt_id BIGINT NOT NULL,
    invoice_id BIGINT NOT NULL,
    allocated_amount DECIMAL(15,2) NOT NULL,
    CONSTRAINT fk_receipt_allocations_receipt
        FOREIGN KEY(receipt_id)
        REFERENCES receipts(receipt_id),
    CONSTRAINT fk_receipt_allocations_invoice
        FOREIGN KEY(invoice_id)
        REFERENCES invoices(invoice_id)
);