CREATE TABLE receipts (
    receipt_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receipt_no VARCHAR(30) NOT NULL UNIQUE,
    customer_id BIGINT NOT NULL,
    receipt_date DATE NOT NULL,
    received_amount DECIMAL(15,2) NOT NULL,
    CONSTRAINT fk_receipts_customer
        FOREIGN KEY(customer_id)
        REFERENCES customers(customer_id)
);