CREATE TABLE shipment_details (
    shipment_detail_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shipment_id BIGINT NOT NULL,
    order_detail_id BIGINT NOT NULL,
    shipped_quantity DECIMAL(15,2) NOT NULL,
    CONSTRAINT fk_shipment_details_shipment
        FOREIGN KEY(shipment_id)
        REFERENCES shipments(shipment_id),
    CONSTRAINT fk_shipment_details_order_detail
        FOREIGN KEY(order_detail_id)
        REFERENCES order_details(order_detail_id)
);