CREATE TABLE sales_returns (
    sales_return_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    return_date DATE NOT NULL
    CONSTRAINT fk_sales_returns_sales_return_customer,
    FOREIGN KEY(customer_id)
    REFERENCES customers(customer_id)
);